#!/bin/sh

. ./pre-backup

echo "backing up /home/alexn ..."

# refresh_access_token obtains a new access token and writes it to stdout
refresh_access_token() {
  curl -s \
    --data-urlencode "client_id=$CLIENT_ID" \
    --data-urlencode "client_secret=$CLIENT_SECRET" \
    --data-urlencode "refresh_token=$REFRESH_TOKEN" \
    --data-urlencode "grant_type=refresh_token" \
    https://oauth2.googleapis.com/token | \
  python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])"
}

tar -cpzf - \
  --directory=/home/alexn \
  --exclude=Downloads \
  --exclude=git_repos \
  --exclude=.cache \
  --exclude=.stack \
  --exclude=.vim \
  --one-file-system \
  . | \
curl -v -s \
  -X PATCH \
  -H "Authorization: Bearer $(refresh_access_token)" \
  -H "Content-Type: application/gzip" \
  --data-binary "@-" \
  "https://www.googleapis.com/upload/drive/v3/files/$FILE_ID?uploadType=media"
